### ISSUE TITLE
Update in the documentation

### ISSUE THREAD

**Issue by madhurinagare** [xcist/documentation#2]
I found some instructions in the documentation are out-dated:

On https://github.com/xcist/documentation/wiki
1. git clone https://github.com/xcist/code.git doesn't work
It should be git clone https://github.com/xcist/CatSim.git 

On https://github.com/xcist/documentation/wiki/Installing-Python, in PyCharm setup
1. Path for HTTP proxy settings is not correct. It should be
File -> Settings... -> Appearance & Behavior -> System Settings -> HTTP Proxy 
2. It should be mentioned that HTTP proxy setting need to be setup according to the user's environment
3. Path for changing configuration should be
Run-> edit configuration 
4. It would be great if we can have more documentation on the code files.

Also, there is an easier way to set up the catsim library with conda and without PyCharm.
>> conda create -n catsimenv python=3.7 
>> conda activate catsimenv
(catsimenv) >> pip install numpy
(catsimenv) >> cd ~/CatSim 
(catsimenv) >> pip install .
(catsimenv) >> cd examples 
(catsimenv) >>python Sim_Sample.py
....
....
Simulation is done
(catsimenv) >> conda deactivate

**Comment by MingyeWu** [comment]
Thank you so much! Some documents are out of date. We have updated the wiki home page.

**Comment by madhurinagare** [comment]
> Thank you so much! Some documents are out of date. We have updated the wiki home page.

Great!
