### ISSUE TITLE
Density volume file

### ISSUE THREAD

**Issue by BBuijtenhuis** [xcist/documentation#3]
Hi there,

I am currently working on a project where XCIST would be of great value.
Now, I would like to create my own 'density volume' and .json files. What is the best method to do this?

Thanks in advance!

**Comment by PaulFitzGerald** [comment]
The .json files are text files, so they can be edited in any text editor. The density files are images, so you will need to create these using software.

As we expand XCIST, we will include more phantoms, and tools to create your own phantoms. Please stay tuned!

We are currently adding documentation. Please check the Wiki (see above menu) periodically.

Thanks for your interest!
Paul
